# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepurl',
            name='fallback_url',
            field=models.CharField(default='', max_length=254, validators=[shortener.validators.validate_url]),
            preserve_default=False,
        ),
    ]
