# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_deepurl_fallback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepurl',
            name='fallback_url',
            field=models.CharField(blank=True, max_length=254, validators=[shortener.validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='deepurl',
            name='shortcode',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
